### ISSUE TITLE
Submitted to Package Control

### ISSUE THREAD

**Issue by mikebranski** [ColibriApps/MonokaiJsonPlus#1]
Just a heads up, I submitted this to Package Control so it's easier for people to install from right inside Sublime Text. Once it gets accepted, the install instructions in the readme can be updated. :)

Pull request: wbond/package_control_channel#4281

**Comment by mikebranski** [comment]
It's been accepted now, so it should be merged in before too long, I'd think. I'll comment back here once I get the notification.

**Comment by mikebranski** [comment]
Hey @benmarten, can you tag the current release for this package? After that it should be all set. I forgot that's needed for Package Control to accept the recipe: https://github.com/wbond/package_control_channel/pull/4281#issuecomment-90091756

Thanks!

**Comment by mikebranski** [comment]
Specifically, the tag should be `1.0.0`.

**Comment by mikebranski** [comment]
@benmarten, @ColibriApps - Could someone with write access to this repo add a semver tag so this can be accepted into Package Control? See [@wbond's comment](https://github.com/wbond/package_control_channel/pull/4281#issuecomment-91456644) and the discussion history for more, but basically someone just needs to tag the latest commit as `1.0.0` - that should be doable right from within GitHub. Thanks!

**Comment by benmarten** [comment]
ok, i've added it...

**Comment by mikebranski** [comment]
Awesome, thanks Ben. :+1:
