### ISSUE TITLE
Weird/ unnecessary tab?

### ISSUE THREAD

**Issue by cachaito** [ColibriApps/MonokaiJsonPlus#2]
Hi! It's a great extension, anyway I have a question: what is code > Monokai in Preferences/ Color Scheme/ Monokai JSON+ tab?

[Sublime Text 3 Build 3084]

![test](https://cloud.githubusercontent.com/assets/4311424/7155360/62b3ec84-e35e-11e4-8e35-565fa2a826af.png)

**Comment by benmarten** [comment]
This came from the development code, it's fixed with the latest version.

**Comment by cachaito** [comment]
Great news! Cheers :-)
