### ISSUE TITLE
MonokaiJson + not working

### ISSUE THREAD

**Issue by rme716** [ColibriApps/MonokaiJsonPlus#4]
I have installed MonokaiJson +, but my .json file is still displayed in plain white text. Is there an additional step that I must do?

**Comment by benmarten** [comment]
No, did you set MonokaiJson+ as your theme?
<img width="808" alt="screen shot 2016-08-24 at 9 42 13 am" src="https://cloud.githubusercontent.com/assets/5960238/17939346/1af056c2-69df-11e6-84dd-24075a994e55.png">

Also is the file syntax set to json?
<img width="548" alt="screen shot 2016-08-24 at 9 42 03 am" src="https://cloud.githubusercontent.com/assets/5960238/17939351/219c87e8-69df-11e6-837f-5b8d8d661632.png">

**Comment by rme716** [comment]
I have done this, but it is still not working.

**Comment by benmarten** [comment]
I just reinstalled and its still working for me...
Maybe you have some other plugins, that interfere with it?
Which version are you using? I'm on Sublime Text 3, Build 3114.

Maybe you could try it with a parallel fresh Sublime Text 2 install?

**Comment by blundell** [comment]
setting the syntax to `json` got it working
